baseURL = "http://localhost/"
languageCode = "en-us"
title = "La Gxoja Filozofio"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  defaultTheme = "auto"  # dark/light mode auto-switching

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2
